<a href="https://colab.research.google.com/github/Shashank-tr-DA/numpy_practical_1/blob/master/numpy_practical.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#How to import numpy in our program to use its functions...
#Use the import keyword 
'''
we give a short name by aliasing to numpy because we use numpy frequently in  
our program so it is easy to write np rather than numpy
''' 

import numpy as np

In [5]:
'''
Now we see how to create numpy array by different methods.. So lets see.
'''

# 1. Using python list

 # First define a list

list_1 = [1, 2, 3, 4, 5, 6]

 # Now create array by using array function

arr_1 = np.array(list_1)
  
print(arr_1)                               

[1 2 3 4 5 6]


In [6]:
# 2. We can also create array by just simply passing the list inside the array function

arr_2 = np.array([1, 2, 3, 4, 5, 6])

print(arr_2)

[1 2 3 4 5 6]


In [7]:
# 3. We can also create an array by list comprehension

arr_3 = np.array([i for i in range(9)])

print(arr_3)

[0 1 2 3 4 5 6 7 8]


In [9]:
# 4. One more take a look

arr_4 = np.array(list(map(int, input("Enter array elements = ").split())))

print(arr_4)

Enter array elements = 1 2 3 4 5 6 7 8
[1 2 3 4 5 6 7 8]


In [ ]:
'''
These are all the method by which you can make an array..
there are lot of more functions by which we can also create array but these 
are fundamentals..

we take a look on all functions of numpy 

Happy learning

'''