<a href="https://colab.research.google.com/github/Shashank-tr-DA/numpy_practical_1/blob/master/numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
As we all see how to make an array now explore soe new things in numpy
'''

import numpy as np

In [2]:
arr_1 = np.array([1,2,3,4,5,6,7,8])

print(arr_1)

[1 2 3 4 5 6 7 8]


In [3]:
# We can check the type of this arr_1 variable 

type(arr_1)

numpy.ndarray

In [4]:
# We can also check dimension of array

arr_1.ndim

1

In [6]:
# Now create 2d array 

arr_2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr_2)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
# Now check dimension

arr_2.ndim

2

In [9]:
# Check the size of array, gives the total no. of elements in array

arr_1.size

8

In [10]:
arr_2.size

8

In [11]:
# Now check the shape how many rows and column

arr_1.shape

(8,)

In [12]:
arr_2.shape

(2, 4)

In [13]:
# Check for data type in array

arr_1.dtype

dtype('int64')

In [14]:
arr_2.dtype

dtype('int64')

In [15]:
# We can also change the data type

arr_3 = np.array([[1,2,3], [4,5,6]], dtype = 'float32')

print(arr_3)

[[1. 2. 3.]
 [4. 5. 6.]]


In [16]:
# now apply all the methods we learn

print(arr_3.size)

print(arr_3.shape)

print(arr_3.dtype)

print(arr_3.ndim)

6
(2, 3)
float32
2


In [17]:
# To create ones matrix we have a function named ones and for zeros we have zeros function

ones_arr = np.ones((3,3))

print(ones_arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
ones_arr = np.ones((3,3), dtype = 'int32')

print(ones_arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [19]:
zero_arr = np.zeros((4,4))

print(zero_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
zero_arr = np.zeros((4,4), dtype = 'int64')

print(zero_arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [21]:
# Now you all think what is int32, int64 these all gives different data size

print(ones_arr.itemsize)

print(zero_arr.itemsize)

4
8


In [23]:
# We can also use data type as bool and string

arr_5 = np.array([[1,0], [0,4]], dtype = 'bool')

print(arr_5)

[[ True False]
 [False  True]]


In [24]:
arr_6 = np.array([[1,0], [2,0]], dtype = 'str')

print(arr_6)

[['1' '0']
 ['2' '0']]
