# In this we see some functions used in numpy 

In [1]:
import numpy as np

## arange()

### It gives the one dimensional array in given range


In [2]:
arr1 = np.arange(1,9)
print(arr1)

[1 2 3 4 5 6 7 8]


In [3]:
arr2 = np.arange(9,19)
print(arr2)

[ 9 10 11 12 13 14 15 16 17 18]


In [4]:
arr3 = np.arange(1,21,2)
print(arr3)

[ 1  3  5  7  9 11 13 15 17 19]


## linspace()

### It gives the desired number of values between a define range

In [5]:
lin_arr = np.linspace(1,11,5) #It gives the 5 value including 1 and 11
print(lin_arr)

[ 1.   3.5  6.   8.5 11. ]


In [6]:
lin_arr2 = np.linspace(0,6,4)
print(lin_arr2)

[0. 2. 4. 6.]


In [7]:
lin_arr3 = np.linspace(1,9,5, dtype = 'int32')
print(lin_arr3)

[1 3 5 7 9]


## reshape()

### It changes the shape of any array into desired shape


In [8]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr.reshape(2,5) #It reshape the 1d array into (2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
# You have to remember that the multiplication of shape given in reshape function is equal to number of 1d array element.

arr_1 = np.arange(1,13)
print(arr_1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [10]:
arr_1.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
arr_1.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
arr_2 = np.arange(1,21)
print(arr_2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [13]:
arr_2.reshape(2,2,5) # 3d array

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

## ravel()

### It converts the any array into 1d array

In [17]:
rav_arr = np.arange(1,13).reshape(3,4)
print(rav_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
rav_arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
rav_arr1 = np.arange(1,9).reshape(2,4)
print(rav_arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [20]:
rav_arr1.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

## flatten()

### It also converts the given array into 1d array but it has different parameter

In [22]:
flat = np.linspace(1,9,8, dtype = 'int').reshape(4,2)
print(flat)

[[1 2]
 [3 4]
 [5 6]
 [7 9]]


In [23]:
flat.flatten() #simple

array([1, 2, 3, 4, 5, 6, 7, 9])

In [24]:
flat.flatten(order = 'C') #By default row wise flat the array into 1d

array([1, 2, 3, 4, 5, 6, 7, 9])

In [28]:
flat.flatten(order = 'F') #flat the array into 1d column wise

array([1, 3, 5, 7, 2, 4, 6, 9])

## transpose() or T

### return the transpose of any matrix

In [29]:
trans = np.arange(1,17).reshape(4,4)
print(trans)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [30]:
trans.transpose()

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [32]:
trans.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])