# In this we see sm mathematical operations and functions as well

In [1]:
import numpy as np

In [4]:
arr1 = np.arange(1,9).reshape(2,4)
arr2 = np.arange(9,17).reshape(2,4)
print(arr1, "\n")
print(arr2)

[[1 2 3 4]
 [5 6 7 8]] 

[[ 9 10 11 12]
 [13 14 15 16]]


In [5]:
arr1 + arr2 #elements wise addition

array([[10, 12, 14, 16],
       [18, 20, 22, 24]])

In [6]:
np.add(arr1, arr2) #We can also do the same by use of this function

array([[10, 12, 14, 16],
       [18, 20, 22, 24]])

In [7]:
arr2 - arr1 #elements wise subtraction

array([[8, 8, 8, 8],
       [8, 8, 8, 8]])

In [8]:
np.subtract(arr2, arr1) #We can also do the same by using this function

array([[8, 8, 8, 8],
       [8, 8, 8, 8]])

In [9]:
arr1 * arr2 #elements wise multiplication

array([[  9,  20,  33,  48],
       [ 65,  84, 105, 128]])

In [10]:
np.multiply(arr1, arr2) #We can also do the same by using this function

array([[  9,  20,  33,  48],
       [ 65,  84, 105, 128]])

In [11]:
arr2 / arr1 #elements wise division

array([[9.        , 5.        , 3.66666667, 3.        ],
       [2.6       , 2.33333333, 2.14285714, 2.        ]])

In [13]:
np.divide(arr2, arr1) #We can also do the same by using this function

array([[9.        , 5.        , 3.66666667, 3.        ],
       [2.6       , 2.33333333, 2.14285714, 2.        ]])

In [14]:
## Now you all want to know that if you want to perform matrix multiplication then

# Here a function that gives you matrix multiplication

In [22]:
arr_1 = np.arange(1,10).reshape(3,3)
print(arr_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
arr_2 = np.arange(10,19).reshape(3,3)
print(arr_1)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [23]:
arr_1 @ arr_2

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [25]:
# We can also use a function named dot

arr_1.dot(arr_2)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

## max()

### it returns the maximum value in array

In [28]:
arr_4 = np.array([[7,3,9], [3,10,4], [12,6,0]])
print(arr_4)

[[ 7  3  9]
 [ 3 10  4]
 [12  6  0]]


In [31]:
arr_4.max()

12

In [33]:
arr_4.max(axis = 1) #gives maximum value from every row

array([ 9, 10, 12])

In [35]:
arr_4.max(axis = 0)#gives maximum value from every column

array([12, 10,  9])

## argmax()

### gives the index of maximum value

In [36]:
arr_4.argmax()

6

In [37]:
arr_4.argmax(axis = 0) #gives index of maximum value from every column

array([2, 1, 0], dtype=int64)

In [38]:
arr_4.argmax(axis = 1) #gives index of maximum value from every row

array([2, 1, 0], dtype=int64)

## min()

### returns the minimum value from an array

In [39]:
arr_4.min()

0

In [40]:
arr_4.min(axis = 0)

array([3, 3, 0])

In [41]:
arr_4.min(axis = 1)

array([3, 3, 0])

## argmin()

### returns the index of minimum value

In [42]:
arr_4.argmin()

8

In [43]:
arr_4.argmin(axis = 0)

array([1, 0, 2], dtype=int64)

In [44]:
arr_4.argmin(axis = 1)

array([1, 0, 2], dtype=int64)

## sum()

### gives the sum of all elements

In [45]:
arr_9 = np.arange(1,13).reshape(3,4)
print(arr_9)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [47]:
np.sum(arr_9)

78

In [48]:
np.sum(arr_9, axis = 0) #sum of all elements column wise

array([15, 18, 21, 24])

In [49]:
np.sum(arr_9, axis = 1) #sum of all elements row wise

array([10, 26, 42])

## mean()

### it gives the mean value of an array

In [50]:
arr5 = np.arange(1,5).reshape(2,2)
print(arr5)

[[1 2]
 [3 4]]


In [51]:
np.mean(arr5)

2.5

In [52]:
np.mean(arr5, axis = 0)

array([2., 3.])

In [53]:
np.mean(arr5, axis = 1)

array([1.5, 3.5])

## sqrt()

### it gives the square root of all the elements of an array

In [55]:
arr6 = np.array([[4,9], [16,25]])
print(arr6)

[[ 4  9]
 [16 25]]


In [56]:
np.sqrt(arr6)

array([[2., 3.],
       [4., 5.]])

## std()

### gives standard deviation

In [57]:
np.std(arr6)

7.88986691902975

## exp()

### gives exponential value

In [58]:
arr6

array([[ 4,  9],
       [16, 25]])

In [59]:
np.exp(arr6)

array([[5.45981500e+01, 8.10308393e+03],
       [8.88611052e+06, 7.20048993e+10]])

## log()

### gives natural log value of all elements in array

In [60]:
np.log(arr6)

array([[1.38629436, 2.19722458],
       [2.77258872, 3.21887582]])

## log10()

### gives value of log base 10 for all elements

In [61]:
np.log10(arr6)

array([[0.60205999, 0.95424251],
       [1.20411998, 1.39794001]])

## Now we see the array slicing

In [62]:
slice_arr = np.arange(1,101).reshape(10, 10)
print(slice_arr)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [63]:
# For first element

In [64]:
slice_arr[0,0]

1

In [65]:
# for first row

In [66]:
slice_arr[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
# for first column

In [69]:
slice_arr[:,0]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [70]:
slice_arr[:, 0:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [71]:
# for any specific segment

In [72]:
slice_arr[2:5, 2:5]

array([[23, 24, 25],
       [33, 34, 35],
       [43, 44, 45]])

In [73]:
#for any specific columns

In [74]:
slice_arr[:, 1:4]

array([[ 2,  3,  4],
       [12, 13, 14],
       [22, 23, 24],
       [32, 33, 34],
       [42, 43, 44],
       [52, 53, 54],
       [62, 63, 64],
       [72, 73, 74],
       [82, 83, 84],
       [92, 93, 94]])

In [76]:
# to access all elements 

In [77]:
slice_arr[::]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [78]:
slice_arr[:, :]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [79]:
slice_arr[:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])